export const addressFields = [
  {
    labelText: "Country",
    labelFor: "country",
    id: "country",
    name: "country",
    type: "text",
    autoComplete: "country",
    isRequired: false,
    placeholder: "Country",
  },
  {
    labelText: "City",
    labelFor: "locality",
    id: "locality",
    name: "locality",
    type: "text",
    autoComplete: "locality",
    isRequired: false,
    placeholder: "City",
  },
  {
    labelText: "Postal Code",
    labelFor: "postalCode",
    id: "postalCode",
    name: "postalCode",
    type: "text",
    autoComplete: "postalCode",
    isRequired: false,
    placeholder: "Postal Code",
  },
  {
    labelText: "Primary",
    labelFor: "primary",
    id: "primary",
    name: "primary",
    type: "checkbox",
    autoComplete: "primary",
    isRequired: false,
    placeholder: "Primary",
  },
  {
    labelText: "State/Province",
    labelFor: "region",
    id: "region",
    name: "region",
    type: "text",
    autoComplete: "region",
    isRequired: true,
    placeholder: "State/Province",
  },
  {
    labelText: "Street",
    labelFor: "streetAddress",
    id: "streetAddress",
    name: "streetAddress",
    type: "text",
    autoComplete: "streetAddress",
    isRequired: false,
    placeholder: "Street",
  },
  {
    labelText: "Type",
    labelFor: "type",
    id: "type",
    name: "type",
    type: "select",
    autoComplete: "type",
    isRequired: false,
    placeholder: "Type",
    list: [
      { key: "work", value: "Work" },
      { key: "home", value: "Home" },
      { key: "other", value: "Other" },
    ],
  },
];
