export const apiFields = [
  {
    labelText: "Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Name",
    category: "settings.general",
  },
  {
    labelText: "Domain",
    labelFor: "domain",
    id: "domain",
    name: "domain",
    type: "text",
    autoComplete: "domain",
    isRequired: true,
    placeholder: "Domain",
    category: "settings.general",
  },
  {
    labelText: "Identifier",
    labelFor: "identifier",
    id: "identifier",
    name: "identifier",
    type: "text",
    autoComplete: "identifier",
    isRequired: true,
    placeholder: "Identifier",
    category: "settings.general",
  },
  {
    labelText: "Token Expiration (Seconds)",
    labelFor: "tokenExpiration",
    id: "tokenExpiration",
    name: "tokenExpiration",
    type: "text",
    autoComplete: "tokenExpiration",
    isRequired: false,
    placeholder: "86400 seconds",
    category: "settings.tokenSetting",
  },
  {
    labelText: "Token Expiration For Browser Flows (Seconds)",
    labelFor: "tokenExpirationBrowser",
    id: "tokenExpirationBrowser",
    name: "tokenExpirationBrowser",
    type: "text",
    autoComplete: "tokenExpirationBrowser",
    isRequired: false,
    placeholder: "7200 seconds",
    category: "settings.tokenSetting",
  },
  {
    labelText: "Signing Algorithm",
    labelFor: "signingAlgorithm",
    id: "signingAlgorithm",
    name: "signingAlgorithm",
    type: "select",
    autoComplete: "signingAlgorithm",
    isRequired: false,
    placeholder: "Signing Algorithm",
    list: [
      { key: "RS256", value: "RS256" },
      { key: "HS256", value: "HS256" },
    ],
    category: "settings.tokenSetting",
  },
  {
    labelText: "RBAC",
    labelFor: "RBAC",
    id: "RBAC",
    name: "RBAC",
    type: "checkbox",
    autoComplete: "RBAC",
    isRequired: false,
    placeholder: "RBAC",
    category: "settings.rbac",
  },
  {
    labelText: "Add Permission in Access Token",
    labelFor: "addPermissionAccessToken",
    id: "addPermissionAccessToken",
    name: "addPermissionAccessToken",
    type: "checkbox",
    autoComplete: "addPermissionAccessToken",
    isRequired: false,
    placeholder: "Add Permission in Access Token",
    category: "settings.rbac",
  },
  {
    labelText: "Allow Skipping User Consent",
    labelFor: "allowSkippingUserConsent",
    id: "allowSkippingUserConsent",
    name: "allowSkippingUserConsent",
    type: "checkbox",
    autoComplete: "allowSkippingUserConsent",
    isRequired: false,
    placeholder: "Allow Skipping User Consent",
    category: "settings.access",
  },
  {
    labelText: "Allow Offline Access",
    labelFor: "allowOfflineAccess",
    id: "allowOfflineAccess",
    name: "allowOfflineAccess",
    type: "checkbox",
    autoComplete: "allowOfflineAccess",
    isRequired: false,
    placeholder: "Allow Offline Access",
    category: "settings.access",
  },
];

export const apiPermissionScopesFields = [
  {
    labelText: "Permission",
    labelFor: "permission",
    id: "permission",
    name: "permission",
    type: "text",
    autoComplete: "permission",
    isRequired: true,
    placeholder: "Permission",
    category: "settings.access.permission",
  },
  {
    labelText: "Description",
    labelFor: "description",
    id: "description",
    name: "description",
    type: "text",
    autoComplete: "description",
    isRequired: true,
    placeholder: "Description",
    category: "settings.access.permission",
  },
];
