export const externalIdentityAccountFields = [
  {
    labelText: "Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Name",
  },
  {
    labelText: "Description",
    labelFor: "description",
    id: "description",
    name: "description",
    type: "text",
    autoComplete: "description",
    isRequired: false,
    placeholder: "Description",
  },
  {
    labelText: "User Id",
    labelFor: "userId",
    id: "userId",
    name: "userId",
    type: "text",
    autoComplete: "userId",
    isRequired: true,
    placeholder: "User Id",
  },
  {
    labelText: "Provider",
    labelFor: "provider",
    id: "provider",
    name: "provider",
    type: "select",
    list: [
      { key: "google", value: "Google" },
      { key: "azure", value: "Azure" },
      { key: "okta", value: "Okta" },
      {
        key: "custom",
        value: "Custom",
      },
    ],
    autoComplete: "provider",
    isRequired: true,
    placeholder: "Provider",
  },
  //   {
  //     labelText: "Provider",
  //     labelFor: "provider",
  //     id: "provider",
  //     name: "provider",
  //     type: "text",
  //     source: {
  //       labelText: "Provider",
  //       labelFor: "provider",
  //       id: "provider_select",
  //       parentId: "provider",
  //       name: "provider_select",
  //       type: "select",
  //       list: [
  //         { key: "google", value: "Google" },
  //         { key: "azure", value: "Azure" },
  //         { key: "okta", value: "Okta" },
  //         {
  //           key: "custom",
  //           value: "Custom",
  //         },
  //       ],
  //       autoComplete: "provider",
  //       isRequired: true,
  //       placeholder: "Provider",
  //       handleChange: (handleChange) => {
  //         return (e) => {
  //           const itemValue = e.target.value;
  //           handleChange(e, itemValue);
  //           return itemValue;
  //         };
  //       },
  //     },
  //     autoComplete: "provider",
  //     isRequired: true,
  //     placeholder: "Provider",
  //   },

  {
    labelText: "Provider User Id",
    labelFor: "providerUserId",
    id: "providerUserId",
    name: "providerUserId",
    type: "text",
    valueType: "array",
    autoComplete: "providerUserId",
    isRequired: true,
    placeholder: "Provider User Id",
  },
  {
    labelText: "Provider Refresh Token",
    labelFor: "Provider Refresh Token",
    id: "providerRefreshToken",
    name: "providerRefreshToken",
    type: "text",
    autoComplete: "providerRefreshToken",
    isRequired: false,
    placeholder: "Provider Refresh Token",
  },
  {
    labelText: "Provider Access Token",
    labelFor: "Provider Access Token",
    id: "providerAccessToken",
    name: "providerAccessToken",
    type: "text",
    autoComplete: "providerAccessToken",
    isRequired: true,
    placeholder: "Provider Access Token",
  },
  {
    labelText: "Provider Access Expires At (Seconds)",
    labelFor: "providerAccessExpiresAt",
    id: "providerAccessExpiresAt",
    name: "providerAccessExpiresAt",
    type: "text",
    autoComplete: "providerAccessExpiresAt",
    isRequired: false,
    placeholder: "36000 seconds",
  },
  {
    labelText: "Provider Scopes",
    labelFor: "providerScopes",
    id: "providerScopes",
    name: "providerScopes",
    type: "textarea",
    valueType: "array",
    autoComplete: "providerScopes",
    isRequired: true,
    placeholder: "Provider Scopes",
  },
  {
    labelText: "Enabled",
    labelFor: "enabled",
    id: "enabled",
    name: "enabled",
    type: "checkbox",
    autoComplete: "enabled",
    isRequired: false,
    placeholder: "Enabled",
  },
];
