const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "text",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "authVerification",
    name: "authVerification",
    type: "password",
    autoComplete: "authVerification",
    isRequired: true,
    placeholder: "Password",
    hiddenUpdate: true,
    hiddenDisplay: true,
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirmPassword",
    id: "confirmPassword",
    name: "confirmPassword",
    type: "password",
    autoComplete: "confirmPassword",
    isRequired: true,
    placeholder: "Confirm Password",
    database: false,
    hiddenUpdate: true,
    hiddenDisplay: true,
  },
];

const domainFields = [
  {
    labelText: "Domain Name",
    labelFor: "domainName",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Domain Name",
  },
  {
    labelText: "Description",
    labelFor: "description",
    id: "description",
    name: "description",
    type: "text",
    autoComplete: "description",
    isRequired: true,
    placeholder: "Description",
  },
  // {
  //     labelText:"Primary",
  //     labelFor:"primary",
  //     id:"primary",
  //     name:"primary",
  //     type:"checkbox",
  //     autoComplete:"primary",
  //     isRequired:false,
  //     placeholder:"Primary",
  //     customClass: "ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"
  // }
];

const companyFields = [
  {
    labelText: "Company Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Company Name",
  },
  {
    labelText: "Display Name",
    labelFor: "displayName",
    id: "displayName",
    name: "displayName",
    type: "text",
    autoComplete: "displayName",
    isRequired: true,
    placeholder: "Display Name",
  },
  {
    labelText: "Description",
    labelFor: "description",
    id: "description",
    name: "description",
    type: "text",
    autoComplete: "description",
    isRequired: true,
    placeholder: "Description",
  },
  // {
  //     labelText:"Primary",
  //     labelFor:"primary",
  //     id:"primary",
  //     name:"primary",
  //     type:"checkbox",
  //     autoComplete:"primary",
  //     isRequired:false,
  //     placeholder:"Primary",
  //     customClass: "ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"
  // }
  // ,
  {
    labelText: "Type",
    labelFor: "type",
    id: "type",
    name: "type",
    type: "select",
    autoComplete: "type",
    isRequired: false,
    placeholder: "Type",
    list: [
      { key: "customer", value: "Customer" },
      { key: "reseller", value: "Reseller" },
    ],
    reseller: true,
  },
];

const userFields = [
  {
    labelText: "User Name",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "User Name",
  },
  {
    labelText: "Display Name",
    labelFor: "displayName",
    id: "displayName",
    name: "displayName",
    type: "text",
    autoComplete: "displayName",
    isRequired: true,
    placeholder: "Display Name",
  },
  {
    labelText: "Notes",
    labelFor: "notes",
    id: "notes",
    name: "notes",
    type: "textarea",
    autoComplete: "notes",
    isRequired: false,
    placeholder: "Notes",
  },
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "text",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "authVerification",
    name: "authVerification",
    type: "password",
    autoComplete: "authVerification",
    isRequired: true,
    placeholder: "Password",
    hiddenUpdate: true,
    hiddenDisplay: true,
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirmPassword",
    id: "confirmPassword",
    name: "confirmPassword",
    type: "password",
    autoComplete: "confirmPassword",
    isRequired: true,
    placeholder: "Confirm Password",
    database: false,
    hiddenUpdate: true,
    hiddenDisplay: true,
  },
];

const groupFields = [
  {
    labelText: "Group Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Group Name",
  },
  {
    labelText: "Display Name",
    labelFor: "displayName",
    id: "displayName",
    name: "displayName",
    type: "text",
    autoComplete: "displayName",
    isRequired: true,
    placeholder: "Display Name",
  },
  {
    labelText: "Notes",
    labelFor: "notes",
    id: "notes",
    name: "notes",
    type: "textarea",
    autoComplete: "notes",
    isRequired: false,
    placeholder: "Notes",
  },
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "text",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email",
  },
];

//signingAlgorithm
export {
  loginFields,
  signupFields,
  domainFields,
  companyFields,
  userFields,
  groupFields,
};
