export const scimFields = [
    {
    labelText: "Id",
    labelFor: "id",
    id: "id",
    name: "id",
    type: "text",
    autoComplete: "off",
    isRequired: true,
    placeholder: "text",
    hiddenUpdate: true,
  },
    {
    labelText: "Scim Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "off",
    isRequired: true,
    placeholder: "Scim Name",
  },
  {
    labelText: "Display Name",
    labelFor: "displayName",
    id: "displayName",
    name: "displayName",
    type: "text",
    autoComplete: "off",
    isRequired: true,
    placeholder: "Display Name",
  },
  {
    labelText: "Notes",
    labelFor: "notes",
    id: "notes",
    name: "notes",
    type: "textarea",
    autoComplete: "notes",
    isRequired: false,
    placeholder: "Notes",
  },
  {
    labelText: "Application",
    labelFor: "applicationId",
    id: "applicationId",
    name: "applicationId",
    type: "select",
    autoComplete: "off",
    isRequired: false,
    placeholder: "Select Application",
    list: [],
  },
  {
    labelText: "Access Token",
    labelFor: "accessToken",
    id: "accessToken",
    name: "accessToken",
    type: "password",
    autoComplete: "new-password",
    isRequired: true,
    placeholder: "Access Token",
    hiddenUpdate: true,
    hiddenDisplay: true,
  },
{
    labelText: "Refresh Token",
    labelFor: "refreshToken",
    id: "refreshToken",
    name: "refreshToken",
    type: "password",
    autoComplete: "new-password",
    isRequired: true,
    placeholder: "Refresh Token",
    hiddenUpdate: true,
    hiddenDisplay: true,
  },
];
