export const tokenExchangePolicyFields = [
  {
    labelText: "Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Name",
    category: "settings.general",
  },
  {
    labelText: "Client ID",
    labelFor: "clientId",
    id: "clientId",
    name: "clientId",
    type: "text",
    readOnly: true,
    autoComplete: "clientId",
    isRequired: true,
    placeholder: "Client ID",
    category: "settings.general",
  },
  ,
  {
    labelText: "Audience Type",
    labelFor: "handlerType",
    id: "handlerType",
    name: "handlerType",
    type: "select",
    list: [
      { key: "google", value: "Google" },
      { key: "azure", value: "Microsoft Graph (Azure)" },
      { key: "okta", value: "Okta" },
      { key: "salesforce", value: "Salesforce" },
      { key: "facebook", value: "Facebook" },
      { key: "unidir", value: "Universal Directory (GoodWorks)" },
      { key: "internal", value: "Internal" },
      {
        key: "custom",
        value: "Custom",
      },
    ],
    readOnly: true,
    autoComplete: "handlerType",
    isRequired: true,
    placeholder: "Google",
    category: "settings.general",
  },
  {
    labelText: "Allowed Subject Audiences",
    labelFor: "allowedSubjectAudiences",
    id: "allowedSubjectAudiences",
    name: "allowedSubjectAudiences",
    type: "textarea",
    valueType: "array",
    autoComplete: "allowedSubjectAudiences",
    isRequired: true,
    placeholder: "Allowed Subject Audiences",
    category: "settings.general",
  },
  {
    labelText: "Allowed Target Audiences",
    labelFor: "allowedTargetAudiences",
    id: "allowedTargetAudiences",
    name: "allowedTargetAudiences",
    type: "textarea",
    valueType: "array",
    autoComplete: "allowedTargetAudiences",
    isRequired: false,
    placeholder: "Allowed Target Audiences",
    category: "settings.general",
  },
  {
    labelText: "Allowed Scopes",
    labelFor: "allowedScopes",
    id: "allowedScopes",
    name: "allowedScopes",
    type: "textarea",
    valueType: "array",
    autoComplete: "allowedScopes",
    isRequired: false,
    placeholder: "Allowed Scopes",
    category: "settings.general",
  },
  {
    labelText: "Max Token Lifetime Seconds (Seconds)",
    labelFor: "maxTokenLifetimeSeconds",
    id: "maxTokenLifetimeSeconds",
    name: "maxTokenLifetimeSeconds",
    type: "text",
    autoComplete: "maxTokenLifetimeSeconds",
    isRequired: false,
    placeholder: "7200 seconds",
    category: "settings.general",
  },
  {
    labelText: "Allow Impersonation",
    labelFor: "allowImpersonation",
    id: "allowImpersonation",
    name: "allowImpersonation",
    type: "checkbox",
    autoComplete: "allowImpersonation",
    isRequired: false,
    placeholder: "Allow Impersonation",
    category: "settings.general",
  },
  {
    labelText: "Allow Delegation",
    labelFor: "allowDelegation",
    id: "allowDelegation",
    name: "allowDelegation",
    type: "checkbox",
    autoComplete: "allowDelegation",
    isRequired: false,
    placeholder: "Allow Impersonation",
    category: "settings.general",
  },
  {
    labelText: "Enabled",
    labelFor: "enabled",
    id: "enabled",
    name: "enabled",
    type: "checkbox",
    autoComplete: "enabled",
    isRequired: false,
    placeholder: "Enabled",
    category: "settings.general",
  },
];
